src/components/LinkPreview.tsx, src/css/custom.css, src/css/sablier.css, src/theme/MDXComponents/A.js
- fixes #1 and #33 by wrapping the icons into explicit fill color controls
- explores #34
=> feat: style enhancements

docs/contracts/v2/reference/core/abstracts/abstract.Adminable.md, docs/contracts/v2/reference/core/abstracts/abstract.SablierV2Base.md, docs/contracts/v2/reference/core/abstracts/abstract.SablierV2Lockup.md, docs/contracts/v2/reference/core/contract.SablierV2Comptroller.md, docs/contracts/v2/reference/core/contract.SablierV2LockupDynamic.md, docs/contracts/v2/reference/core/contract.SablierV2LockupLinear.md, docs/contracts/v2/reference/core/contract.SablierV2NFTDescriptor.md, docs/contracts/v2/reference/periphery/contract.SablierV2Archive.md, docs/contracts/v2/reference/periphery/contract.SablierV2ProxyPlugin.md, docs/contracts/v2/reference/periphery/contract.SablierV2ProxyTarget.md, scripts/autogen.sh
=> fix: fix hyperlinks in reference

docs/concepts/05-governance.md, docs/concepts/06-glossary.md, docs/contracts/v1/guides/deployments.md, docs/contracts/v2/02-deployments.md, docs/contracts/v2/guides/create-stream/01-lockup-linear.mdx, docs/contracts/v2/guides/create-stream/02-lockup-dynamic.mdx, docs/contracts/v2/guides/stream-management/01-setup.md, docusaurus.config.js
=> feat: prop up deployments and governance

docs/contracts/v2/02-deployments.md, docs/contracts/v2/reference/05-errors.md
Closes https://github.com/sablier-labs/v2-docs/issues/40
=> refactor: update errors page

docs/concepts/protocol/02-stream-types.mdx, docs/concepts/protocol/05-statuses.md
Closes #20, and partially addresses #13 by adding a statuses diagram.
=> refactor: update statuses page

docs/concepts/02-sablier-protocol.md, docs/concepts/05-governance.md, docs/concepts/06-glossary.md, docs/concepts/protocol/06-fees.mdx, docs/concepts/protocol/07-flash-loans.mdx, docs/contracts/v2/guides/05-flash-loans.md
perf: capitalize Protocol Admin
refactor: remove Flash Loans section in Fees
refactor: remove Flash Loans section in Glossary
=> refactor: disable flash loan pages

docs/contracts/v2/reference/02-diagrams.md
Closes https://github.com/sablier-labs/v2-docs/issues/61.
Due to the customizability limitations of Mermaid.js, the diagrams may not have an ideal visual appearance. However, they have been improved in terms of accurately representing the actual flows.
<details>
<summary> Click to expand </summary>
</details>
<details>
<summary> Click to expand </summary>
</details>
=> Improve diagrams 

docs/contracts/v2/guides/01-local-environment.md
Closes #https://github.com/sablier-labs/v2-docs/issues/73.
=> fix: fix integration template url

docs/concepts/05-governance.md, docs/contracts/v2/02-deployments.md
=> feat: base deployment

docusaurus.config.js, static/js/crisp-chat.js, tsconfig.json
=> feat: crisp chat

docs/api/subgraphs/04-queries.md, docs/api/subgraphs/architecture/02-structure.mdx, docs/apps/02-features.mdx, docs/concepts/03-use-cases.mdx, docs/concepts/06-glossary.md, docs/concepts/protocol/02-stream-types.mdx, docs/concepts/protocol/03-segments.md, docs/concepts/protocol/07-flash-loans.mdx, docs/contracts/v2/guides/05-hooks.md, docs/contracts/v2/guides/proxy-architecture/01-overview.mdx, docs/contracts/v2/guides/proxy-architecture/03-batch-stream.mdx, docs/contracts/v2/guides/proxy-architecture/04-single-stream.mdx, docs/contracts/v2/reference/02-diagrams.md
=> fix: typos

docs/contracts/v2/03-security.md, docs/contracts/v2/guides/_category_.json, docs/contracts/v2/reference/_category_.json
=> docs: add security page

docs/concepts/protocol/02-stream-types.mdx
=> Improve exponential function plots to end at (100,100)

docs/concepts/06-glossary.md, docs/concepts/protocol/07-fees.mdx
Closes #116.
1. Adds definition of Gas fee in Glossary
2. QnA related to Gas fees in the fees section.
=> feat: add information about gas fees

docs/apps/features/02-airstreams.mdx, docs/apps/guides/03-csv-support.mdx
=> feat: add timezone info for airstream and csvs

docs/api/merkle-api/02-functionality.mdx
This PR includes documentation about the new authentication 
Should be merged in https://github.com/sablier-labs/docs/pull/138 before the launch.
=> Feat: api authentication info box

.eslintrc.yml
=> chore: fix eslint parser

docs/apps/guides/03-csv-support.mdx
Context here: https://github.com/sablier-labs/v2-interfaces/issues/999
cc @sablier-labs/frontend for review
=> refactor: update date format

docs/contracts/v2/guides/10-custom-deployments.mdx
Closes https://github.com/sablier-labs/docs/issues/173.
cc @smol-ninja and @andreivladbrg — could you lend me a hand here?
I am not up to speed with the latest way in which we make deployments nowadays.
I suppose we might need to open source the Warp Drive scripts? If yes, let's put them in the [GitHub Wiki](https://github.com/sablier-labs/v2-core/wiki/Deployments).
=> docs: custom deployment guide

docs/contracts/v2/02-deployments.md, docs/contracts/v2/deployments/v2.0.md, docs/contracts/v2/deployments/v2.1.md
Introduces a new category in the deployments page: _Mainnets_ and _Testnets_.
=> refactor: separate deployments

docusaurus.config.ts
=> fix: fix stale links

docs/apps/01-overview.mdx, docs/apps/03-branding.mdx, docusaurus.config.ts
Flagged by Ahrefs as an issue:
=> refactor: use https

docs/contracts/v2/guides/09-etherscan.md, docusaurus.config.ts, src/constants/links.ts
Should fix the Ahrefs error [3XX page receives organic traffic](https://app.ahrefs.com/site-audit/7006528/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CcontentType%2Cdepth%2Credirect%2CincomingAllLinks&current=26-09-2024T120143M0400&filterId=3d66ed31d2074c0e138a751d2520f95a&issueId=c64d34be-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating).
=> refactor: update blog url

docs/concepts/protocol/09-hooks.md, docs/contracts/v1/contracts/constant-functions.md, docs/contracts/v1/guides/getting-started.md, docs/contracts/v2/guides/06-hooks.md, docusaurus.config.ts, src/constants/links.ts
Increase our SEO backlinks by pointing to `discord.sablier.com`
=> refactor: update discord URL

docs/contracts/v2/guides/09-etherscan.md, docusaurus.config.ts, src/constants/links.ts
Context on [Slack](https://sablier.slack.com/archives/C0322QL7KT9/p1727780209065829).
=> refactor: blog urls

static/robots.txt
Add `robots.txt` and disallow indexing ⤵️
=> chore: add robots.txt

docs/api/flow/02-endpoints.mdx
This pr aims to update the flow subgraph endpoints in the docs.
=> chore: update flow subgraph endpoints

docs/api/airdrops/02-endpoints.mdx, docs/api/flow/02-endpoints.mdx, docs/api/lockup/02-endpoints.mdx, docs/apps/guides/01-csv-support.mdx, docs/concepts/01-what-is-sablier.mdx, docs/concepts/lockup/03-segments.md, docs/guides/lockup/05-etherscan.md, docs/guides/lockup/examples/stream-management/04-renounce.md, docs/reference/flow/01-diagrams.md, docs/snippets/EnvioTip.mdx, docs/snippets/TheGraphSunset.mdx
FYI @sablier-labs/engineers, we can reuse MDX components, see `TheGraphSunset` and `EnvioTip` in this PR.
=> refactor: rewordings

docs/guides/flow/examples/01-local-environment.md, docs/guides/flow/examples/02-calculate-rps.mdx, docs/guides/flow/examples/03-create-stream.mdx, docs/guides/flow/examples/04-stream-management.mdx, docs/guides/flow/examples/05-batchable.mdx
Polishing https://github.com/sablier-labs/docs/pull/209
=> docs: flow examples polish

docs/api/airdrops/02-endpoints.mdx, docs/api/airdrops/deprecated/01-old-endpoints.mdx, docs/api/airdrops/deprecated/_category_.json, docs/api/flow/02-endpoints.mdx, docs/api/flow/deprecated/01-old-endpoints.mdx, docs/api/flow/deprecated/_category_.json, docs/api/lockup/02-endpoints.mdx, docs/api/lockup/deprecated/01-old-endpoints.mdx, docs/api/lockup/deprecated/_category_.json, docs/api/lockup/the-graph/02-structure.mdx, docs/guides/lockup/02-deployments.md, docs/snippets/DeprecatedEndpoints.mdx, docs/snippets/DepricationWarning.mdx
This pr aims to update all the new subgraphs and mention the deprication of the old ones.
=> chore: update subgraph endpoints and anounce subgraphs deprecation

docs/api/airdrops/the-graph/01-entities.mdx, docs/guides/airdrops/02-deployments.md, docs/guides/flow/02-deployments.md, docs/guides/lockup/02-deployments.md, docs/guides/lockup/examples/staking/04-stake.md
I few minor issues I found in the docs.
=> docs: nitpick

docs/api/lockup/01-overview.mdx, docs/api/lockup/the-graph/02-structure.mdx, docs/api/lockup/the-graph/04-queries.md, docs/apps/guides/01-csv-support.mdx, docs/concepts/11-fees.mdx, docs/guides/flow/examples/04-stream-management.mdx, docs/guides/lockup/05-etherscan.md, docs/reference/airdrops/03-access-control.md
Fix broken [link](https://app.ahrefs.com/site-audit/7006528/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Cdepth%2Ccompliant%2CincomingAllLinks%2Corigin&compare=05-02-2025P0100&filterId=28daa554b6921b6c6742b8b3f34bbf51&issueId=c64dae3f-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating&udUrl=https%3A%2F%2Fdocs.sablier.com%2Freference%2Fairdrops%2Fairdrops%2Fcontracts%2Fcontract.SablierMerkleFactory)
=> fix: seo broken links

docs/api/07-legacy.mdx, docs/api/airdrops/02-endpoints.mdx, docs/api/airdrops/06-previous-endpoints.mdx, docs/api/flow/02-endpoints.mdx, docs/api/flow/05-previous-endpoints.mdx, docs/api/lockup/02-endpoints.mdx, docs/api/lockup/05-previous-endpoints.mdx, docs/snippets/DeprecatedSubgraphs.mdx, docs/snippets/EnvioEndpoints.mdx, docs/snippets/EnvioTip.mdx, docs/snippets/TheGraphEndpoints.mdx, docs/snippets/TheGraphSunset.mdx
In preparation for https://github.com/sablier-labs/deployments/issues/21
Note: the diff may appear large but there aren't that many changes. It's just the length of the tables that changed because of Prettier auto-formatting
=> refactor: simplify and improve writing in Endpoints

docs/concepts/12-fees.mdx
I received some feedback that the fees page may be a bit confusing to novice users.  This addition to the top of the page attempts to help clarify things for people who may not have a good understanding of how fees on a public blockchain work.
=> Adds introduction sentence to fee page.

.github/workflows/deploy.yml
Closes https://github.com/sablier-labs/docs/issues/294
=> ci: cache node modules

docs/concepts/07-chains.mdx, docs/concepts/11-governance.md, docs/concepts/12-fees.mdx, docs/guides/airdrops/02-deployments.md, docs/guides/flow/02-deployments.mdx, docs/guides/lockup/02-deployments.mdx
Mock token deployed at [0xa4777CA525d43a7aF55D45b11b430606d7416f8d](https://seitrace.com/address/0xa4777CA525d43a7aF55D45b11b430606d7416f8d)
=> chore: add sei evm deployment

docs/concepts/07-chains.mdx
PRB, I have made you the co-author of this PR.
=> docs: add note about chains supported on UI

docs/concepts/lockup/05-statuses.md
Closes https://github.com/sablier-labs/docs/issues/307
=> fix: correct cold status description

docs/api/01-overview.mdx, docs/api/07-legacy.mdx, docs/api/airdrops/02-airdrops-endpoints.mdx, docs/api/airdrops/06-previous-endpoints.mdx, docs/api/flow/02-flow-endpoints.mdx, docs/api/flow/05-previous-endpoints.mdx, docs/api/lockup/02-lockup-endpoints.mdx, docs/api/lockup/05-previous-endpoints.mdx
Same as https://github.com/sablier-labs/interfaces/pull/1646
=> refactor: update graph user id

bun.lock, package.json, src/components/organisms/AskCookbook.tsx, src/pages/index.tsx
Preview link: https://sablier-docs-q2ui2qy1b-cookbookdev.vercel.app/
Cookbook's Ask Cookbook AI assistant and co-pilot is trained on all existing Sablier resources (source code, docs website, etc.) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about using Sablier, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity coding co-pilot.
Ask Cookbook AI can also access context from thousands of data sources indexed by Cookbook.dev in addition to Sablier-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer …
=> feat(Chef AI):Cookbook Chef AI integration
