sablier-labs/docs

docs/contracts/v2/reference/02-diagrams.md
=> feat: add Lockup Linear and Lockup Dynamic diagrams

docs/apps/05-url-schemes.mdx, docs/apps/integrations/_category_.json
Ref https://github.com/sablier-labs/v2-docs/pull/89#issuecomment-1679441694.
We would ideally nest the "Stream Page", "Create Stream Autofill", and the "Search Streams" in child pages under "URL Schemes", but I'll let you decide @razgraf. All I care is removing the "Integrations" section, which we don't need.
=> refactor: remove "Integrations" nesting

docs/contracts/v2/guides/create-stream/01-lockup-linear.mdx, docs/contracts/v2/guides/create-stream/02-lockup-dynamic.mdx, docs/contracts/v2/guides/proxy-architecture/03-batch-stream.mdx
- there are links to https://docs.sablier.com/contracts/v2/guides/proxy-architecture in the docs which is broken this pr fixes that
=> fixes broken proxy architecture links

docs/contracts/v2/guides/01-local-environment.md
We forgot to update the docs after [updating](https://github.com/sablier-labs/sablier-v2-integration-template/pull/1) the integration template to use Node.js packages.
This PR also closes #106.
=> fix: use Node.js in local environment docs

docs/contracts/v2/02-deployments.md
**Later edit:** mainnet deployment is live
The mainnet contract is not yet deployed due to high ETH gas prices at the moment
=> feat: add SablierV2ProxyTargetApprove deployments

docs/concepts/protocol/02-stream-types.mdx
Couldn't find a better place to put this gas costs.
Also, I want to mention that these may not be accurate with how much the end user will pay when using the app, as it uses the `batch` contract to create single streams. 
Also explained in this PR: https://github.com/sablier-labs/examples/pull/30
=> feat: add gas costs for the shapes in stream types section

docs/contracts/v2/guides/01-local-environment.md
In the PR https://github.com/sablier-labs/examples/pull/20, the [test](https://github.com/sablier-labs/examples/blob/c73ec1d13b5d1756d775679729a9f180d2031c8a/v2/core/LockupLinearStreamCreator.t.sol) referenced in the [documentation](https://docs.sablier.com/contracts/v2/guides/local-environment#run-a-fork-test) was removed and a [new one](https://github.com/sablier-labs/examples/blob/5def4951adbdf3c3f5131f59afcd4f334e0cb759/v2/core/LockupStreamCreator.t.sol) was created.
=> fix: invalid link for stream creator test

src/constants/links.ts
In the section https://docs.sablier.com/concepts/use-cases#3-transparency the link [`here`](https://app.sablier.com/stream/LL-50-40/) leads to a stream that no longer exists
=> fix: invalid link to stream example

docs/contracts/v2/05-gas-benchmarks.md, formatter.js, package.json
Now that benchmark table is manually added to the docs, I have added a formatter code to format numbers to use xxx,xxx,xxx number format.
=> style: add benchmark table formatter

docs/concepts/protocol/08-fees.mdx
There's a jarring typo in the fees docs that can be found here => https://docs.sablier.com/concepts/protocol/fees 
The docs have the following typo "The Sablier Protocol is entirely free to use. There is no protocol fee. However, external integrators who manage their own UI may charge broker `free` in exchange for providing their services".
It should be  `broker fee` instead of `broker free`. I fixed that typo.
=> change typo in  docs/docs/concepts/protocol/08-fees.mdx

docs/concepts/flow/01-overview.md, docs/concepts/flow/02-statuses.md, docs/concepts/lockup/06-statuses.md, docs/concepts/lockup/07-hooks.md, docs/reference/flow/01-diagrams.md, docs/reference/flow/03-access-control.md, docs/reference/lockup/01-diagrams.md, docs/reference/lockup/04-access-control.md
Closes https://github.com/sablier-labs/docs/issues/72.
1. Uses sequence diagrams for actor based flow charts
2. [Lockup Hooks preview](https://v2-docs-jjd1n7mda-sablier.vercel.app/concepts/lockup/hooks#visual-representation)
3. [Airstream Campaign preview](https://v2-docs-jjd1n7mda-sablier.vercel.app/reference/lockup/diagrams#airstream-campaign)
4. [Token Flows](https://v2-docs-jjd1n7mda-sablier.vercel.app/reference/flow/diagrams#token-flows)
5. Adds [a new diagram in Flow](https://v2-docs-git-feat-sequence-diagrams-sablier.vercel.app/reference/flow/diagrams#flow-actors-with-actions)
=> feat: sequence diagrams

docs/guides/flow/02-deployments.md
This PR introduces the `flow` deployed addresses across all chains that `lockup` protocol is deployed.
=> feat: add flow deployments addresses

docusaurus.config.ts
Fix page has links to [broken page.](https://app.ahrefs.com/site-audit/7006528/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CcontentType%2Cdepth%2ClinksInternal4xx%2ClinksCountInternal4xx%2ClinksExternal4xx%2ClinksCountExternal4xx&filterId=ef910605970b081acfca3ff161170299&issueId=c64daf06-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating)
=> fix: support how to 404

docs/apps/guides/02-url-schemes.mdx, docs/concepts/01-what-is-sablier.mdx, docs/concepts/07-nft.mdx, docs/concepts/10-governance.md, docs/concepts/12-security.md, docs/concepts/13-glossary.md, docs/guides/04-custom-deployments.mdx, docs/guides/06-frontend.md, docs/reference/01-overview.md, docs/reference/06-errors.md, docs/support/01-faq.mdx
cc @smol-ninja since I think you were the one who made this change
I think we should restrict the word 'protocol' to the underlying blockchain architecture used
i.e. every token distribution product shipped by Sablier on the EVM will be part of the same unified _Sablier Protocol_
One and only!
=> refactor: singular protocol

docs/concepts/07-chains.mdx, docs/concepts/08-nft.mdx, docs/concepts/09-cancelability.md, docs/concepts/10-transferability.md, docs/concepts/11-governance.md, docs/concepts/12-fees.mdx, docs/concepts/13-security.md, docs/concepts/14-glossary.md, docs/guides/04-custom-deployments.mdx, docs/guides/airdrops/02-deployments.md, docs/guides/flow/02-deployments.mdx, docs/guides/lockup/02-deployments.mdx
This PR adds the supported networks table in the documentation. The following changes have been made:
- Added networks: BNB Smart Chain, Blast, Chiliz Chain, Ethereum Sepolia, Gnosis, IoTeX, Lightlink, Linea, Mode, Morph, Optimism Sepolia, Polygon, Scroll, Superseed, Tangle, XDC, zkSync Era
These updates ensure that the documentation reflects the latest supported networks and provides accurate information for users.
Closes [Add a table with all the chains Sablier is available on](https://github.com/sablier-labs/docs/issues/260)
=> chore: added supported networks table in documentation

docs/guides/flow/04-gas-benchmarks.md, docs/guides/lockup/04-gas-benchmarks.md
Adds a config column to the benchmark tables
closes [Add new "config" column for benchmark tables](https://github.com/sablier-labs/docs/issues/270)
=> docs: Add new config column for linear, dynamic and tranched streams benchmark tables.

docs/concepts/lockup/02-stream-shapes.mdx, docs/guides/flow/04-gas-benchmarks.md, docs/guides/lockup/04-gas-benchmarks.md
closes [Refer to benchmarks repo for gas reference](https://github.com/sablier-labs/docs/issues/256)
=> docs: updates references to the benchmark code.

docs/concepts/12-fees.mdx
The first 3 questions in the Gas Fees section are not about gas fees, which can cause confusion to readers.  I moved them to a new FAQ section, but there may be a better way to handle this.
One question is about how Interface and Contract fees interact, so it doesn't seem quite right for either section.  One is a Q&A about Interface fees specifically so it could be moved into that section, but currently that section is not in Q&A form.
It is also worth noting that the Gas Fees section is in Q&A format while the other two sections are in a more prose-like format, it may be worth making the Gas Fees section format match the Interface and Contract fees sections in writing style.
=> Moves non-gas Q&A to new section.

docs/concepts/12-fees.mdx
Closes https://github.com/sablier-labs/docs/issues/298
I could have replaced the old fee, but I thought it would nice to show it s a timeline. As the table grows, we will find a better way to display the same.
=> docs: update airdrops fee

docs/api/airdrops/06-previous-endpoints.mdx, docs/api/flow/05-previous-endpoints.mdx, docs/api/lockup/05-previous-endpoints.mdx
The old endpoints are still hosted on the historical Subgraph Studio account
=> fix: update incorrect URLs for previous endpoints

src/components/organisms/AdminsTable.tsx
Currently, the [admin URL links](https://docs.sablier.com/concepts/governance#admins) point to the `SablierLockup` contract instead of the admin address. For example, this:
points to: https://abscan.org/address/0x14Eb4AB47B2ec2a71763eaBa202a252E176FAE88%7D
(also incorrect `%7D`)
---
Also, I noticed that because we’re retrieving the address on-chain, it takes a couple of seconds to load and shows this:
Wouldn't it be better to declare them in a simple table?
=> fix: correct hyperlink for admins
